### ISSUE TITLE
Add support to other platforms

### ISSUE THREAD

**Issue by insidegui** [caiyue1993/IceCream#1]
It shouldn't be too hard to add support to macOS, tvOS and watchOS

**Comment by caiyue1993** [comment]
Yep. It shouldn't be too hard.

Anyone who's familiar with macOS, tvOS and watchOS please feel free to contribute to this project!

This issue will keep open for the later contributors.

**Comment by Zasuk** [comment]
i've added the target for tvOS but it is untested. You can try and merge it...

https://github.com/Zasuk/IceCream

**Comment by Zasuk** [comment]
Done

**Comment by caiyue1993** [comment]
#79 & #85 are merged. Now IceCream is available on every Apple platform! 🙌
