### ISSUE TITLE
Callback for starting and finishing synchronization objects

### ISSUE THREAD

**Issue by phuongvb** [caiyue1993/IceCream#102]
When application launches for first time, it needs time to synchronize data, but I can not find in readme or example any callback to know whether app is synchronizing or finish. Is there anyway to detect those events?

**Comment by mobileonekh** [comment]
Yes, this is very important? Otherwise what should we tell user? Ask them to wait 5 minutes, 10 minutes and then try again?

**Comment by iPhoNewsRO** [comment]
i created a pull request that notify the client after a sync: https://github.com/caiyue1993/IceCream/pull/117

**Comment by caiyue1993** [comment]
Check the latest #141. Now you could start syncing manually and get the completionHandler when finishes by invoking `pull(completionHandler:)` method.
