### ISSUE TITLE
CreamAsset uniqueFileNames are duplicated

### ISSUE THREAD

**Issue by julianschiavo** [caiyue1993/IceCream#110]
When creating CreamAssets using the following example code:

```swift
CreamAsset.create(objectID: uniquelyGeneratedUUID, propName: "image", data: imageData)
```

The `uniqueFileName` is duplicated in the Realm database.

## Expected behavior
The `uniqueFileName` would be saved once.

## Actual behavior
The `uniqueFileName` is saved multiple times.

<img width="480" alt="screen shot 2019-01-26 at 2 42 29 pm" src="https://user-images.githubusercontent.com/19729335/51783690-9d475280-2178-11e9-8169-796dd52f65ae.png">

**Comment by caiyue1993** [comment]
Yep I've noticed this, too. 

However it will not affect the performance of syncing process as the rows in the table of `CreamAsset` will not uploaded to CloudKit. We could dig further into this issue.

**Comment by owenzhao** [comment]
This is a known issue of Realm 5.x on earlier versions. https://github.com/realm/realm-cocoa/issues/6662

It has been fixed. So you should not see this on the latest Realm.
