### ISSUE TITLE
Carthage build broken

### ISSUE THREAD

**Issue by aehlke** [caiyue1993/IceCream#113]
## Expected behavior
Carthage build works

## Actual behavior(optional)
Receive this error during the build:
```
error: Build input file cannot be found: '/Users/[...]/Carthage/Checkouts/IceCream/IceCream/Classes/Cream.swift'
```

## Steps to reproduce the problem(optional)

Xcode 10.1, `github "caiyue1993/IceCream" == 1.8.0`, `carthage update IceCream --platform iOS`

**Comment by caiyue1993** [comment]
Hi @aehlke , this bug was fixed in #112 . And since it's not been tagged now, you could build Carthage via the command below:
`github "caiyue1993/IceCream" "master"`

Thanks for your feedback!
