### ISSUE TITLE
How would I be able to only back up to my CloudKit server only when I want to? (e.g. With a click of a button)

### ISSUE THREAD

**Issue by jamesryu108** [caiyue1993/IceCream#114]
How would I be able to only back up to my CloudKit server only when I want to? (e.g. With a click of a button)

**Comment by caiyue1993** [comment]
You could directly move the initialization process of `SyncEngine` into your action block. And `pushAll()` method should be called to achieve your goal.

However, this implementation way of syncing process is NOT recommended as it's not delta update. Calling `pushAll()` will push all existing data to the CloudKit which is wasting of resources.
