### ISSUE TITLE
use custom container fail

### ISSUE THREAD

**Issue by ansonsiva** [caiyue1993/IceCream#115]
I'm trying to use custom container to share date between an macOS app and iOS app. But I found it always use default container even I select specify custom container in Xcode. 

After 1 hour google, I found this solution https://forums.developer.apple.com/thread/95638.

`public init(objects: [Syncable], container: CKContainer = CKContainer.default(), in realm: Realm = try! Realm())
`

After I change the `CKContainer.default()` to `CKContainer.init(identifier: "custom container")`, the problem is solved.

Is there any easy way to use custom container or am I missing something?

**Comment by caiyue1993** [comment]
Just like you said, SyncEngine has provided `public init(objects: [Syncable], container: CKContainer = CKContainer.default(), in realm: Realm = try! Realm())` method and you just need to pass the `CKContainer.init(identifier: "custom container")` to the container parameter.

It will suit your needs.
