### ISSUE TITLE
Item not syncing to cloudkit

### ISSUE THREAD

**Issue by iPhoNewsRO** [caiyue1993/IceCream#119]
I'm working on a to do list app and i currently have this model for the Task item:

```
class TaskModel: Object {
    @objc dynamic var id = NSUUID().uuidString
    @objc dynamic var content = ""
    @objc dynamic var date: Date?
    @objc dynamic var priority = 10
    @objc dynamic var isDeleted = false
    @objc dynamic var isCompleted = false
    let comments = List<CommentModel>()
    
    override class func primaryKey() -> String? {
        return "id"
    }
    
    convenience init(title: String, date: Date?, priority: Int?, comments: List<CommentModel>) {
        self.init()
        
        self.content = title
        self.date = date
        if let priority = priority {
            self.priority = priority
        }
        for comment in comments {
            self.comments.append(comment)
        }
    }
}
```

here is Comment model:

```
class CommentModel: Object {
    @objc dynamic var id = NSUUID().uuidString
    @objc dynamic var content = ""
    @objc dynamic var date = NSDate.init()
    @objc dynamic var isDeleted = false
    
    override class func primaryKey() -> String? {
        return "id"
    }
    
    convenience init(title: String, date: Date) {
        self.init()
        
        self.content = title
        self.date = date as NSDate
    }
}
```

Everything is well, all my Task items are syncing into cloudkit, thanks to IceCream. But not the Comments items.
For example, a Task with 2 comments will sync without comments. If i turn on airplane mode, the comments stay after app restart but as soon as i turn off airplane mode and the sync finish, comments are gone.

Any help?

**Comment by lzyy** [comment]
try `LinkingObjects` ? like in this demo: https://github.com/caiyue1993/IceCream/blob/master/Example/IceCream_Example/Person.swift#L17

more info here: https://github.com/caiyue1993/IceCream/pull/74

**Comment by caiyue1993** [comment]
Hi @iPhoNewsRO , the comment that @lzyy answered is right. You could try using `LinkingObjects`.
As for the time being, `List` with custom types in Realm is not supported yet. We'll support that in the future.

**Comment by iPhoNewsRO** [comment]
thank you, i migrated to `LinkingObjects` and now it's working as expected!
