### ISSUE TITLE
Ambiguous variable name

### ISSUE THREAD

**Issue by Cunqi** [caiyue1993/IceCream#120]
https://github.com/caiyue1993/IceCream/blob/452db699e8970fc589205919452de2023ebc7636/IceCream/Classes/SyncEngine.swift#L212

`(dict, syncEngine)` should be renamed to `(dict, syncObject)`

**Comment by caiyue1993** [comment]
Hi @Cunqi , thanks for your reminder. I'll correct it later or you could create a pr for us. Appreciate it!

**Comment by caiyue1993** [comment]
Already fixed it in this commit: afebc8a0883d9724a6adda263d5110eb833634d0
