### ISSUE TITLE
How to upload all changes in realm database to the iCloud, instead of just one added item?

### ISSUE THREAD

**Issue by jamesryu108** [caiyue1993/IceCream#121]
Here is a snippet of code inside of application(_:willFinishLaunchingWithOptions:) method in AppDelegate.swift:

// This code will determine whether user subscribed for premium feature:
var premiumStatus: Bool? = UserDefaults.standard.bool(forKey: "premium")

// Then there is code that takes to iCloud server. What this means is that database in iCloud server will not be updated when a row of data is added to Realm database.

if let premiumStatus2 = premiumStatus {
            if premiumStatus2 == true {
                syncEngine = SyncEngine(objects: [
                    SyncObject<purchaseList>()
                    ])
            }
        }

Firstly, let's pretend I wrote to purchaseList when not subscribed. (premiumStatus == false) So there is one row of data in realm db in the phone.
Secondly, let's pretend I wrote to purchaseList after getting subscription (premiumStatus == true). So there should be another row of data in realm db in the phone.
Then my phone gets wiped out. I reinstall my app. I should see two items in purchaseList when I reopen my app. However, I only see the second item. It looks like first item that was added to purchaseList was not uploaded to iCloud server. Behavior that I expected was that since iCloud would have blank purchaseList, it should have uploaded two items to it. How can I mitigate this problem?

**Comment by caiyue1993** [comment]
Hi @jamesryu108 , calling `pushAll` method at a proper time might suit your needs.

**Comment by jamesryu108** [comment]
Thanks for that. It works. I read the documentation and you said that pushAll() method should not be used too often. Why is that? What would be the consequence of that?
