### ISSUE TITLE
Syncing between iOS and MacOS

### ISSUE THREAD

**Issue by lasys** [caiyue1993/IceCream#122]
Hi!

At the moment I’m trying to sync data between an iOS App and a MacOS App.
But the MacOS App is never getting a notification. Syncing between two iPhones is working.
I'm using the same Cloudkit container in both Applications. 
Does someony have any advice or any working example for MacOS?

Thank you very much!

_AppDelegate on MacOS:_

    @NSApplicationMain
    class AppDelegate: NSObject, NSApplicationDelegate {

    var syncEngine: SyncEngine?
    
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Insert code here to initialize your application
        syncEngine = SyncEngine(objects: [SyncObject<Cat>()])

        NSApp.registerForRemoteNotifications()
    }

    func application(_ application: NSApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("registered")
    }
    
    func application(_ application: NSApplication, didReceiveRemoteNotification userInfo: [String : Any]) {
        print("didReceive")
    }
    
    func applicationWillTerminate(_ aNotification: Notification) {
        // Insert code here to tear down your application
    }
    }`

**Comment by caiyue1993** [comment]
Hi @lasys, 

I've added a macOS example project for your reference. Below are some important points:

1. You should add some notification code in `didReceiveRemoteNotification` delegate method
2. Make sure the CloudKit container identifier of macOS project is the same as iOS project both in the capability panel and `SyncEngine` initializer.

Turn to #157 for your references.
