### ISSUE TITLE
Question to the author and anyone else using this framework on their apps: Does this work with Swift 5

### ISSUE THREAD

**Issue by jamesryu108** [caiyue1993/IceCream#123]
> Below is the issue template. You can fill each part then submit your issue. 
> Or you can just delete all of these and describe your questions in you-like style. 
> But please remember: the more detailed info you offered, the greater possibility your problem will be solved. 😜

## Expected behavior

// Please replace this line with your expected behavior.

## Actual behavior(optional)

// Please replace this line with the actual behavior.

## Steps to reproduce the problem(optional)

// Please provided to steps to reproduce the problem

## Reference links(optional)

// Please offer the reference links to us. We appreciate it.

**Comment by jamesryu108** [comment]
I am asking because I have not yet upgraded to Swift 5 and I am going to within next few days.

**Comment by caiyue1993** [comment]
Hi @jamesryu108 , as the [Migrating to Swift 5](https://swift.org/migration-guide-swift5/#using-carthagecocoapods-projects) said:

> It is not necessary to migrate your source dependencies as long as they can build in Swift 4/4.2 mode.

Since IceCream could be built in Swift 4/4.2 mode, you can still use IceCream when upgrading your project to Swift 5. And however, we'll upgrade IceCream to Swift 5 later.

**Comment by jamesryu108** [comment]
Thank you. And I really appreciate good work you did in creating this framework.
