### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [caiyue1993/IceCream#125]
I'm using a custom database protocol in my application (to support switching Realm for something else easily). For example, saving an object looks like this:

    public func save(_ object: Storable, completion: ((Bool, Storable) -> ())?) {
        do {
             try self.safeWrite {
                realm.add(object as! Object)
                completion?(true, object)
            }
        } catch {
            print("Unexpected error: \(error).")
            completion?(false, object )
        }
    }

Now, whenever I call this code nothing is synchronized to `CloudKit`. Since *nothing* happens, I don't really know a good path to debug this. Any ideas?

**Comment by Sjoerdjanssenen** [comment]
Could it be related to the following?

In my application the database code is located in a separate database framework. That's where the code above is located. The extensions on the models for conformance to `CKRecordConvertible` and `CKRecordRecoverable` are located in the app.

**Comment by Sjoerdjanssenen** [comment]
However, when I add the framework to my database framework, the app will throw this error:

    Terminating app due to uncaught exception 'RLMException', reason: 'RLMObject subclasses with the same name cannot be included twice in the same target. Please make sure 'CreamAsset' is only linked once to your current target.'

**Comment by SteliosRammos** [comment]
Any news on that issue?

**Comment by Sjoerdjanssenen** [comment]
No news yet, I think.

**Comment by AhsanFazal** [comment]
I have exactly the same issue as @Sjoerdjanssenen.

**Comment by caiyue1993** [comment]
Hi @Sjoerdjanssenen , the usage `realm.add(object as! Object)` will not work with IceCream. As IceCream will observe objects which conform to `Object & CKRecordConvertible & CKRecordRecoverable` and the downcast process will lose these info.
