### ISSUE TITLE
Ambiguous use of 'firesOnRecordCreation'

### ISSUE THREAD

**Issue by huanglins** [caiyue1993/IceCream#127]
![image](https://user-images.githubusercontent.com/10528244/56860803-1733e580-69cd-11e9-9c6e-8ce43a046d83.png)

**Comment by caiyue1993** [comment]
@ianbradbury-bizzibody Have you encountered the same issue? How did you fix it?

**Comment by ianbradbury-bizzibody** [comment]
I updated the code to:

```
let subscription = CKQuerySubscription(
            recordType: syncObject.recordType,
            predicate: predict,
            options: [CKQuerySubscription.Options.firesOnRecordCreation,                CKQuerySubscription.Options.firesOnRecordDeletion,
                CKQuerySubscription.Options.firesOnRecordUpdate]
        )
```

I am running these versions.

Using IceCream (1.8.1)
Using Realm (3.14.0)
Using RealmSwift (3.14.0)

Doing some more testing right now.

**Comment by ianbradbury-bizzibody** [comment]
I've updated to the following versions:

Installing IceCream (1.9.0)
Installing Realm (3.14.2)
Installing RealmSwift (3.14.2)
Installing RxRealm (0.7.6)
Installing RxSwift (4.5.0)

And the CKQuerySubscription.Options.x still compiles.

**Comment by caiyue1993** [comment]
Thanks @ianbradbury-bizzibody , I'll fix it by adding the prefix.

**Comment by Fogh** [comment]
Any release planned with this fix?

**Comment by caiyue1993** [comment]
Hi all, [1.9.1](https://github.com/caiyue1993/IceCream/releases/tag/1.9.1) has been released to fix this issue. Check that out.
