### ISSUE TITLE
Split CloudKit requests into smaller chunks

### ISSUE THREAD

**Issue by IngmarStein** [caiyue1993/IceCream#13]
IceCream does not split CloudKit requests into smaller chunks in `syncObjectsToCloudKit`. This can lead errors such as the following:

```
Error: Your request contains 492 items which is more than the maximum number of items in a single request (400)
```

Realm collection notifications can easily contain many items (e.g. due to https://github.com/realm/realm-cocoa/issues/3494 or during a bulk import). Most of the times, it can be worked around on the application level, but I think the library should handle this case gracefully.

## Expected behavior

All modified objects are updated in CloudKit.

## Actual behavior(optional)

The CloudKit request fails with the error above.

**Comment by insidegui** [comment]
@caiyue1993 This can be fixed by splitting the items into batches of at most 400 at a time.

**Comment by caiyue1993** [comment]
@IngmarStein Thanks a lot for raising this issue and detailed suggestions! IceCream library truly should handle this case. 

And yep, we could fix this by the way @insidegui suggested.

I'm on it and keep tuned.

**Comment by harryworld** [comment]
In practice, we always handle these following errors:

1. `limitExceeded` 400 records per operation, or 2MB per request -> Split it
2. `quotaExceeded` iCloud space is used up -> Show alert message
3. `partialFailure` in case of using default savePolicy

In addition, one may optionally handle the unrecoverable errors like

1. `unknownItem`
2. `internalError`

**Comment by caiyue1993** [comment]
@harryworld I appreciate it a lot! 
Thanks for you practical advice and I'll check out my code. 👍

**Comment by randycarney** [comment]
I just submitted a pull request from my fork CKErrorHandler to address the errors specifically where appropriate, based on the error handling from the GitHub library EVCloudKitDao: https://github.com/evermeer/EVCloudKitDao.

It basically divides all the potential CKError codes into CKErrorTypes that you can switch on and handle with custom code. 

```
 public enum CKErrorType {
        case success
        case retry(afterSeconds: Double)
        case recoverableError(reason: CKFailReason)
        case chunk
        case fail(reason: CKFailReason)
    }

public enum CKFailReason {
        case changeTokenExpired
        case quotaExceeded
        case partialFailure
        case serverRecordChanged
        case shareRelated
        case unhandledErrorCode
        case unknown
    }
```

It also provides a NSLog message copied from the Apple Documentation that could be turned into a button to notify the user easily.

I implemented CKErrorHandler in all the places in SyncEngine it would be currently appropriate as far as I can tell. 

I also made the CKModifyRecordsOperation .isAtomic flag true to avoid CKError.partialFailure errors, though some may want to handle those specifically. 

Let me know what you think!

**Comment by caiyue1993** [comment]
@IngmarStein @harryworld @insidegui 

Gentlemen, I've received a pull request from @randycarney  and made lots of changes to that. And I am really happy to announce that: 

IceCream is equipped with a powerful **ErrorHandler** now!

For the details, you guys could take a look the #15. In that pr, `ErrorHandler` has taken care of all the error codes that CloudKit returns. 

Check it now! Thanks to all of you.

**Comment by jamesryu108** [comment]
> @caiyue1993 This can be fixed by splitting the items into batches of at most 400 at a time.

And how do we do that?
