### ISSUE TITLE
Is there any method to stop and start the sync?

### ISSUE THREAD

**Issue by Lizonlin** [caiyue1993/IceCream#135]

**Comment by caiyue1993** [comment]
No, I'm afraid not. Thanks.

**Comment by caiyue1993** [comment]
However, we provide `pull` and `pushAll` method in the `SyncEngine`. You could check that out if suit you needs.

**Comment by johnnyperdomo** [comment]
@Lizonlin I might have found a way to do it.

**Comment by johnnyperdomo** [comment]
do you still face the issue?

**Comment by johnnyperdomo** [comment]
Either set the syncEngine with objects; or nil, and then decide if you want force push or pull all objects from or to cloudkit.

if stopping:
```swift
syncEngine = nil  //won't fetch or write any cloudkit records
```

if starting: 
```swift
syncEngine = SyncEngine(objects: [SyncObject<YourObject>()])  //set objects ro sync
syncEngine?.pushAll() //force push local changes to cloudkit
```
