### ISSUE TITLE
Realm Crash with Xcode 11 / iOS 13 Beta

### ISSUE THREAD

**Issue by julianpomper** [caiyue1993/IceCream#139]
## Expected behavior

work with Xcode 11 Beta and iOS 13

## Actual behavior(optional)

Realm crashes with `Primary Key for a particular RealmObject not found`

## Steps to reproduce the problem(optional)

Start and run a project with Xcode 11 Beta on iOS 13

## Reference links(optional)

There is already an open issue in the realm-cocoa repo : https://github.com/realm/realm-cocoa/issues/6163

I do not know if it belongs here but I just wanted to point out that there is an issue with realm and the new betas. Just to keep that in mind.

**Comment by caiyue1993** [comment]
Hi @julianpomper , as you said this should be an issue of Realm instead of IceCream. I'll update the dependency after the new release of Realm. Thanks again for your remind.

**Comment by caiyue1993** [comment]
Close this as https://github.com/realm/realm-cocoa/issues/6163 has been resolved
