### ISSUE TITLE
Initializer for conditional binding must have Optional type, not 'URL'

### ISSUE THREAD

**Issue by bradenboothby** [caiyue1993/IceCream#144]
Hello. I keep getting the following error in the CreamAsset file: "Initializer for conditional binding must have Optional type, not 'URL'"

<img width="690" alt="Screen Shot 2019-06-29 at 11 51 39 AM" src="https://user-images.githubusercontent.com/37314746/60386561-6a292800-9a64-11e9-916a-55104c910134.png">

**Comment by caiyue1993** [comment]
Hi, I'm wondering whether you're using your own extension against `CKAsset` and there is a computer property called the same name as `fileURL` which is the type of `URL`. At the same time please check your dependencies, good luck :)

**Comment by Marlon-Monroy** [comment]
@bradenboothby  did you ever fix this issue? am getting the same error.
