### ISSUE TITLE
Carthage build failing

### ISSUE THREAD

**Issue by real1900** [caiyue1993/IceCream#145]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream/IceCream.xcodeproj -scheme IceCream-macOS -configuration Release -derivedDataPath /Users/sulemanimdad/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/IceCream/1.10.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/bv/bbhjyw3j0ws8lbfpzr72spfr0000gn/T/IceCream SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/bv/bbhjyw3j0ws8lbfpzr72spfr0000gn/T/carthage-xcodebuild.KqXzcI.log

....

The log file says: 

org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/IceCream/1.10.0/Build/Intermediates.noindex/ArchiveIntermediates/IceCream-macOS/IntermediateBuildFilesPath/IceCream.build/Release/IceCream-macOS.build/Objects-normal/x86_64/SyncEngine.o
/Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream/IceCream/Classes/SyncEngine.swift:18:34: error: use of undeclared type 'DatabaseManager'
    private let databaseManager: DatabaseManager
                                 ^~~~~~~~~~~~~~~
/Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream/IceCream/Classes/SyncEngine.swift:33:35: error: use of undeclared type 'DatabaseManager'
    private init(databaseManager: DatabaseManager) {
                                  ^~~~~~~~~~~~~~~
/Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream/IceCream/Classes/SyncEngine.swift:23:42: error: use of unresolved identifier 'PrivateDatabaseManager'
            let privateDatabaseManager = PrivateDatabaseManager(objects: objects, container: container)
                                         ^~~~~~~~~~~~~~~~~~~~~~
/Users/sulemanimdad/Documents/Developer/Submission/Submission/submission-framework-ios/Carthage/Checkouts/IceCream/IceCream/Classes/SyncEngine.swift:26:41: error: use of unresolved identifier 'PublicDatabaseManager'
            let publicDatabaseManager = PublicDatabaseManager(objects: objects, container: container)
                                        ^~~~~~~~~~~~~~~~~~~~~

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by caiyue1993** [comment]
Thanks for submitting this issue. It is due to some new files have not been added into IceCream macOS/watchOS/tvOS target. I've already fixed it in the latest 1.10.1 release. Please check that out. 
Thank you again :)
