### ISSUE TITLE
Does Cream Asset delete automatically when deleting object?

### ISSUE THREAD

**Issue by johnnyperdomo** [caiyue1993/IceCream#151]
My question is whether Icecream automatically removes deletes Cream Assets if the user deletes data record?

``` swift

//Model Class
@objc dynamic var id = ""
@objc dynamic var asset: CreamAsset?
@objc dynamic var isDeleted = false

//
try! realm.write {
     data.isDeleted = true
 }

```

Does IceCream automatically delete Cream Asset from the local device? Or would it need to written like this? ⬇

``` swift

//....
try! realm.write {
     data.isDeleted = true
     CreamAsset.deleteCreamAssetFile(with: data.id)
 }

```

**Comment by caiyue1993** [comment]
Hi @johnnyperdomo , great question. However there is no need to add `CreamAsset.deleteCreamAssetFile(with: data.id)` in your code as IceCream will automatically clear the data which marked `isDeleted` when app terminates. If you want to find the details, this line could be a key https://github.com/caiyue1993/IceCream/blob/e66225ae7c91ec8f2bce8ce62ddf7079ce0e1e28/IceCream/Classes/PrivateDatabaseManager.swift#L120
