### ISSUE TITLE
Toggle CloudKit Sync

### ISSUE THREAD

**Issue by johnnyperdomo** [caiyue1993/IceCream#156]
Is there any way to let the user disable/enable cloud kit sync manually?

![alt text](http://www.uidownload.com/files/1014/482/429/ios7-switches-psd.jpg)

Is there a way to implement this with icecream?

# Expected Behavior
1. User disables sync -> Local changes only
2. User enables sync -> Local changes and remote cloud changes sync successfully. (local changes that were made before 'enable sync' should sync as well)

**Comment by caiyue1993** [comment]
No, I'm afraid not. This is not by design.
