### ISSUE TITLE
My primary keys stored as strings are converted to integers causing a crash. "1234" should not be converted to 1234 without checking the schema.

### ISSUE THREAD

**Issue by michaelforrest** [caiyue1993/IceCream#158]
## Expected behavior
My model's primary key is defined as a string and should be treated as such by IceCream.

## Actual behavior(optional)
IceCream assumes that if my primaryKey _can_ be interpreted as an integer then it should convert it before using it in a realm query ([this line](https://github.com/caiyue1993/IceCream/blob/master/IceCream/Classes/CKRecordRecoverable.swift#L98)).

 Since some of my primary keys are technically interpretable as integers (e.g. `"12345"`), this causes a crash. 

The `primaryKeyForRecordID(recordID:)` method should be changed to determine the primary key type from the schema instead of making this incorrect assumption.

## Steps to reproduce the problem(optional)

Use a string `"1234"` as a primary key in a record. It will crash when it tries to sync.

**Comment by caiyue1993** [comment]
Hi @michaelforrest ,

Thanks a lot for pointing out this issue in clear words! 
Already fixed it in #165. Check that out :)

**Comment by michaelforrest** [comment]
Looks good, thanks!
