### ISSUE TITLE
Can't sync when Appstore release version, but can sync on build version

### ISSUE THREAD

**Issue by MovingOnnn** [caiyue1993/IceCream#159]
## Expected behavior

sync on Appstore release version
## Actual behavior(optional)
Can't sync on Appstore release version, but can sync on debug version
// Please replace this line with the actual behavior.

## Steps to reproduce the problem(optional)
1.I migrate Realm object in didFinishLaunchingWithOptions function in AppDelegate
(I add primary key for my FifthObject when migrating )

    let realmconfig = Realm.Configuration(
      schemaVersion: 29,
      migrationBlock: { migration, oldSchemaVersion in
        migration.enumerateObjects(ofType: "FifthObject", { (oldObject, newObject) in
          if oldSchemaVersion < 21 {
            // Realm will automatically detect new properties and removed properties
            // And will update the schema on disk automatically
            newObject!["id"] = UUID().uuidString
          }
        })

        print("Migration complete.")
    })

    
    Realm.Configuration.defaultConfiguration = realmconfig

2.I tried to start sync in didFinishLaunchingWithOptions function in AppDelegate.
` syncEngine = SyncEngine(objects: [
      SyncObject<FirstObject>(),
      SyncObject<SecondObject>(),
      SyncObject<ThirdObject>(),
      SyncObject<FourthObject>(),
      SyncObject<FifthObject>()
      ])
`

Sync didn't work on release version.Very Weird.When I run my code on computer it works totally fine! But downloading from App Store version doesn't sync.

**Comment by MovingOnnn** [comment]
@caiyue1993 or any other clever guys! Please help.

**Comment by caiyue1993** [comment]
Sorry, if everything works fine in the development environment, it's not a problem of IceCream. And please pay attention to this in the README file:
> If you're going to launch your app onto App Store, don't forget to deploy your environment settings to production. You can do it easily in the CloudKit Dashboard. Write & Read permissions are also need to be considered.

And if problem still occurs, please refer to the Apple official docs regarding how to deploy to the production mode.

**Comment by h85579049** [comment]
Hi @caiyue1993, sorry but it's not clear that what I have to change in cloudkit dashboard?, and what do you mean by write & read permission (doesn't it get assigned automatically to record?, for the development it already assigned public as I have setup in my code)

**Comment by aehlke** [comment]
@h85579049 you get it by now?
