### ISSUE TITLE
Readme file and more than one realm object support

### ISSUE THREAD

**Issue by WillBoland** [caiyue1993/IceCream#16]
Is what's shown on the read me the only required setup?
What if we have more than one realm object (EX: dog and human classes)

**Comment by caiyue1993** [comment]
Sure. Readme file shows lots of thing. But the subscription process has been ignored. You can check it in example project. It's much easier than you think. :)

For the second question, see #8. It will be supported very soon.

**Comment by caiyue1993** [comment]
#8
