### ISSUE TITLE
Support SPM

### ISSUE THREAD

**Issue by ivanvorobei** [caiyue1993/IceCream#162]
`Swift Package Manager` simple integrate. Maybe added it?

**Comment by ivanvorobei** [comment]
Also it allow using `Catalyst`

**Comment by anonrig** [comment]
Any updatees on SPM support?

**Comment by ivanvorobei** [comment]
Realm now supported `SPM`.

**Comment by caiyue1993** [comment]
Hi buddies, I'm working on it. And if you are in a hurry, why not submit a PR for us? 😀

**Comment by tzechuen** [comment]
Hey guys, I've created a pull request here for SPM support:

https://github.com/caiyue1993/IceCream/pull/171

**Comment by caiyue1993** [comment]
Hi buddies,
#171 was merged and it works nicely. Thank you again @tzechuen !

**Comment by ivanvorobei** [comment]
@tzechuen many thanks!
