### ISSUE TITLE
Am I missing something simple? Can't get sync to work!

### ISSUE THREAD

**Issue by jshrager** [caiyue1993/IceCream#163]
I have struggled to implement this library and realise before giving up I should post this and see if i'm missing something very simple.

- I have installed library with Cocoapods
- I added the code to App Delegate as per this example https://github.com/caiyue1993/IceCream/blob/master/Example/IceCream_Example/AppDelegate.swift
- I set the sync service to just be for two of my models as a trial
- I added the two delegates to the two models I'm wanting to sync, using this example from the readme (i added isDeleted also)

extension Dog: CKRecordConvertible {
    // Leave it blank if you are using private database
    // For public database users, uncomment the following code:
    // static var databaseScope: CKDatabase.Scope {
    //     return .public
    // } 
}

extension Dog: CKRecordRecoverable {
    // Leave it blank
}

including the isDeleted property to CKRecordConvertible

- I am logged into iCloud on my phone and the simulator
- When I open the app and create a new entry for the two models, they are saved to local Realm fine, but nothing appears in iCloud.
- I get the occasional 'zone not found error' which I checked has been fixed already
- When i log into the iCloud dashboard with the same iCloud account I don't see any data or anything in the logs.
- I've tried adding the syncService.pushAll() to the app delegate, going back to home and reopening app, but again nothing.

Am I forgetting to do something incredibly simple? I can't understand why I wouldn't get it working if it's working for most people!

**Comment by EricWiener** [comment]
@jshrager did you ever figure out what was wrong?

**Comment by kishinmanglani** [comment]
@jshrager @EricWiener Also experiencing the same issue. Any luck?

**Comment by EricWiener** [comment]
@kishinmanglani I did eventually get it to work in 2 production apps. I would recommend trying:
1. Make sure you are actually starting the sync engine. Calling push and pull won't start the sync engine, just pull changes
2. Make sure you are restarting the sync engine each time the app opens
3. Make sure your schemas are valid and match what's in iCloud for both production and development. If the schemas aren't correct, just manually add the fields yourself
4. Check your logs to make sure no errors are appearing. If you see any batch operation failed, look through the batch for the route cause of the batch failing.
5. Production and development versions of the app sync to different iCloud databases. If you install a production version over a development version, the development iCloud database will still be used. You need to delete the development version first.

**Comment by EricWiener** [comment]
@kishinmanglani for sure and I would manually create the schemas in iCloud dashboard. The first time I used IceCream sync it manually created the zones for me, but it never did it again. 

Your initialization looks correct to me. Likely if you manually create the zones, it will hopefully start working.
