### ISSUE TITLE
Invalid assumptions of child property type (String/Int)

### ISSUE THREAD

**Issue by meteochu** [caiyue1993/IceCream#167]
In the commit,  17ded32, changes were done to support identifying String/Int-based primary key objects. However in the following line, this assumption is invalid:

https://github.com/caiyue1993/IceCream/blob/0a26bdc90ecaef8d2cb6214a09f6c4e990defffe/IceCream/Classes/CKRecordRecoverable.swift#L79-L81

`primaryKeyForRecordID` is called on `T.self` which is the parent object, we need to instead check the type of primaryKey for _that_ child type instead of using the parent object. 

i.e. the following will be broken (assuming that `id` for both classes are the primaryKey for each class). When CKRecordRecoverable tries to decode the object, it'll use the parent's type in the above snippet (String) but the primaryKey is actually an Int for the child. 

```
class Parent: Object {
    @objc dynamic var id: String = ""
    @objc dynamic var child: Child?
}

class Child : Object {
    @objc dynamic var id: Int = 0
}
```

**Comment by caiyue1993** [comment]
#168 has been merged to fix this issue. 
Thank you again @meteochu! Great work!
