### ISSUE TITLE
Xcode Crashes When SyncEngine is Called in App Delegate

### ISSUE THREAD

**Issue by WillBoland** [caiyue1993/IceCream#17]
**EDIT:** I traced it to the Cream.swift file's init. This occurs when the Realm is Encrypted.

I recently incorporated IceCream into my project, and after code setup through looking at Example Project and the Docs, Xcode crashes (and the app) when `syncEngine = SyncEngine<MyRealmClassHere>()` is called in AppDelegate. This only occurs when AppleID is signed in. 

Details: Swift 4, Xcode 9.1 (9B55), iPhone 6 Simulator

## Expected behavior

Code execution goes as normal, no crash. SyncEngine runs.

## Actual behavior(optional)

Run project, Xcode crashes upon app start up. I have tracked it down to SyncEngine crashes Xcode and app only when AppleID is logged in, regardless of whether it can connect to any data or not (EX: wifi off).

## Steps to reproduce the problem(optional)

1. Set up according to documentation, also looking at example project.
2. Run SyncEngine after Realm Migration. I tried it before migration, same error.

**Comment by caiyue1993** [comment]
Hi @WillBoland. So what's the exception/crash massage that Xcode gives you?

**Comment by WillBoland** [comment]
<img width="1654" alt="screen shot 2017-12-13 at 8 26 20 pm" src="https://user-images.githubusercontent.com/32425172/33970976-06e10b9a-e044-11e7-995f-182b50bbeff1.png">

It is because in the Cream.swift file, it is not checking for a encrypted realm, but opening the default realm. I suggest changing it so that it can open an encrypted realm as well.

Another solution would be to never use an encrypted realm; however, it appears to be hard to migrate from an encrypted realm back to the default.

**Comment by caiyue1993** [comment]
Thanks for the details.

I am sorry for IceCream not supporting encrypted realm for the time being. Since adding support for encrypted realm will increased workload to a large extent, I am not going to add this issue to to-do list for now.

But if you really wanna use IceCream to sync encrypted realm, you could fork this project and add some the changes yourself. It should work!

And I'll let you know when IceCream supports encrypted realm in the future.

Thanks @WillBoland !

**Comment by caiyue1993** [comment]
For the late comers, the intro of encrypted realm is [here](https://academy.realm.io/posts/tim-oliver-realm-cocoa-tutorial-on-encryption-with-realm/).
