### ISSUE TITLE
Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.

### ISSUE THREAD

**Issue by huanglins** [caiyue1993/IceCream#173]
<img width="960" alt="截屏2019-11-20下午5 35 13" src="https://user-images.githubusercontent.com/10528244/69227013-1c9c8b80-0bbc-11ea-88e2-3efc5dc738d0.png">
程序启动后，BackgroundWorker 没有在主线程中执行报错。

**Comment by caiyue1993** [comment]
Please provide more context about this situation. For example, tell us when you invoke `add(record:)` method so that we could dig further into this.
