### ISSUE TITLE
SPM version outdated for realm

### ISSUE THREAD

**Issue by anonrig** [caiyue1993/IceCream#176]
The latest version for Realm Cocoa is 4.1.1 but currently SPM uses 3.20.0

Realm Cocoa releases: https://github.com/realm/realm-cocoa/releases
Packge.swift file: https://github.com/caiyue1993/IceCream/blob/master/Package.swift

**Comment by caiyue1993** [comment]
Thanks for submitting the issue. Turn to #177

**Comment by anonrig** [comment]
@caiyue1993 you need to bump the package version in order to update swift package manager.

**Comment by caiyue1993** [comment]
👌👀
