### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by joelkraut** [caiyue1993/IceCream#18]
It would be great to be able to install this via Carthage as well as CocoaPods!

**Comment by caiyue1993** [comment]
Thanks @joelkraut ! It will be supported very soon.

**Comment by joelkraut** [comment]
Great :)

**Comment by caiyue1993** [comment]
Since the IceCream relies on RealmSwift framework and the example project has a dependency of `RxRealm`, it could be somehow difficult to work out this issue. 

So I've tagged "help wanted" tag and I hope someone who is quite familiar with Carthage could help me to solve this problem. And I will be on this issue all the time. 

Please be patient and keep tuned.

**Comment by caiyue1993** [comment]
Anyone who wants to give help could checkout out the [feature/support-carthage](https://github.com/caiyue1993/IceCream/branches) and start from it. 

Thanks.

**Comment by caiyue1993** [comment]
Hi @joelkraut , I wanna bring some good news.

After my days' trial, now IceCream is able to be installed via Carthage!

However, the change has largely changed the folder structure of IceCream. So I temporarily put this support in the `feature/carthage-support` branch of this project. You may easily check it. 

The temporary usage is as follows:
1. Add `github "caiyue1993/IceCream" "feature/carthage-support"` into your Cartfile of your own project.
2. Run `carthage update` 
3. In the step 2, Carthage will download and build the `IceCream.framework`, `Realm.framwork` and `RealmSwift.framwork` for you. Just drag this 3 framework to your project. 
4. Don't forget to add to your Run Script just as [Carthage](https://github.com/Carthage/Carthage) indicated!

And when the `feature/carthage-support` branch be merged into master, I'll just let you know and close this issue. For the time being, you could just be the first man to try it. 🙂

**Comment by joelkraut** [comment]
That’s great!! Thanks for your hard work!

**Comment by remaerd** [comment]
我 Fork 了项目之后发现原来已经有一个 Carthage Branch 了，为何没有合并到 Master 里面呢？貌似 Carthage Branch 已经落后于 master Branch 了。有人可以帮帮忙合并吗？

**Comment by caiyue1993** [comment]
@remaerd Sorry for the delay. I'll merge the branch these days :)

**Comment by caiyue1993** [comment]
Hi @joelkraut @remaerd , good news again.

Now IceCream has successfully supported Carthage!  🎉

Check the instructions on [README](https://github.com/caiyue1993/IceCream#carthage).
