### ISSUE TITLE
Not deleting local data

### ISSUE THREAD

**Issue by minimaluminium** [caiyue1993/IceCream#183]
Setting `isDeleted = true` deletes the remote data, but the local data stays.

```swift
try! realm.write {
  object.isDeleted = true
}
```

Should I manually delete the object with `realm.delete()` as well?

```swift
try! realm.write {
  object.isDeleted = true
  realm.delete(object)
}
```

**Comment by minimaluminium** [comment]
Another self-closing issue 😬
I've actually had to filter the data to fetch with `.filter("isDeleted = false")` and observe it.

Hope these issues will help others who are just getting started with Realm and IceCream.

**Comment by EricWiener** [comment]
Thanks for posting @minimaluminium . Saved me a ton of time seeing this. If anyone sees this and is using RealmJS with IceCream, note that this should be `.filtered('isDeleted = false')`.

**Comment by minimaluminium** [comment]
@EricWiener I'm glad it helped! :)

**Comment by EricWiener** [comment]
To add something to this thread, I needed to delete CreamAssets from a `doc` object while leaving the object they belong to. I tried to do this at first with:

```
 CreamAsset.deleteCreamAssetFile(with: doc.id)
```

but I got the error:
```
ErrorHandler.Fail: Invalid Arguments: the specified request contains bad information.CKError.Code: 12
```

I was able to successfully remove the cream assets by just setting their properties to nil in a realm write:
```
doc.image = nil
```

**Comment by minimaluminium** [comment]
I haven't had a chance to work with CreamAssets yet. Thanks for sharing your experience, will definitely keep that in mind.
