### ISSUE TITLE
Only one CreamAsset per Object?

### ISSUE THREAD

**Issue by pazrob** [caiyue1993/IceCream#184]
> I have an postObject that contains up to 10 photos. 

> Could I have list of CreamAsset?  
let assets = List<'CreamAsset'>()

> Or should I have 10 different CreamAsset properties?
var assets1: CreamAsset?
var assets2: CreamAsset?
...

> Thank you!

**Comment by caiyue1993** [comment]
Hi @pazrob ,
For now, IceCream prefers the latter way to support multiple CreamAsset properties.
