### ISSUE TITLE
How to use it  in Objective project?Thx

### ISSUE THREAD

**Issue by ArcasGuo** [caiyue1993/IceCream#187]
> Below is the issue template. You can fill each part then submit your issue. 
> Or you can just delete all of these and describe your questions in you-like style. 
> But please remember: the more detailed info you offered, the greater possibility your problem will be solved. 😜

## Expected behavior

// Please replace this line with your expected behavior.

## Actual behavior(optional)

// Please replace this line with the actual behavior.

## Steps to reproduce the problem(optional)

// Please provided to steps to reproduce the problem

## Reference links(optional)

// Please offer the reference links to us. We appreciate it.

**Comment by caiyue1993** [comment]
Hi, I believe your question is "how to use Swift framework in Objective-C codebase"? You could turn to this Apple [doc](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c) for more details
