### ISSUE TITLE
Underscore as primary key

### ISSUE THREAD

**Issue by Cliff-F** [caiyue1993/IceCream#190]
Thank you for the great framework.

There's an issue.
The recordName used in CKRecord.ID does not allow a name that starts with an underscore.
However, it is allowed as a primary key of a swift object. 
One of my record had a primary key that started with an underscore, which caused sync issues.
It should be better to have a checking procedure or throwing an error when a primary key starts with an underscore.

**Comment by caiyue1993** [comment]
😀Thanks for opening this issue and #191 has been merged to resolve this.
