### ISSUE TITLE
Remove the need for manual serialization of records

### ISSUE THREAD

**Issue by insidegui** [caiyue1993/IceCream#2]
It would be cool if this could leverage `Codable` or some other mechanism so we didn't have to manually serialize/deserialize the records.

**Comment by caiyue1993** [comment]
Great suggestions. I will work on it to replace the current.

**Comment by evermeer** [comment]
Shameless self promotion tip 😊: You could use EVReflection for automatic serialisation of RealmObjects and CKRecords.

See https://github.com/evermeer/EVReflection/tree/master/Source/Realm and https://github.com/evermeer/EVReflection/tree/master/Source/CloudKit

And if you do choose for Codable then maybe this can help: https://github.com/evermeer/Stuff#codable

**Comment by insidegui** [comment]
@caiyue1993 Realm has builtin reflection. You can use the `sharedSchema` on Realm objects to get the schema, which allows you to list properties (including types and other goodies).

**Comment by caiyue1993** [comment]
@insidegui Yep, I've found that and things become much easier now. I am refactoring it with excitement.

**Comment by caiyue1993** [comment]
Hi guys @insidegui @evermeer. I'm almost finished, the usage has been muuuch easier now by only **adding one line of code**! See #6 for more info.

**Comment by caiyue1993** [comment]
@insidegui I haven't used Codable cause I find it's hard to dynamically generate CodingKeys in Codable. 

Thanks to protocol extensions in Swift, users no longer need to handle configurable stuffs themselves.

I am going to close this issue. 😝

**Comment by insidegui** [comment]
Well done 🎉
