### ISSUE TITLE
One to Many Relationships not supported

### ISSUE THREAD

**Issue by fstigre** [caiyue1993/IceCream#202]
First of all, let me thank you all for the awesome framework, I can't believe how easy it is to sync data with `IceCream` it is really like magic.

I currently have a project where I'm using a One-to- many relationships in Realm using the List method `let dogs = List<Dog>()` but I tried it and `IceCream` does not create the right relationship in `CloudKit` dashboard.

Can someone please confirm that `let dogs = List<Dog>()` is not supported in `IceCream` and that the only option would be using the LinkingObject option, `let dogs = LinkingObjects(fromType: Dog.self, property: "owner")`?

Thanks a lot!

**Comment by caiyue1993** [comment]
Yes, I can confirm that. We're still working on the support of `List` data structure.

**Comment by fstigre** [comment]
Thank you for the confirmation. Keep up the good work, IceCream it's awesome!

**Comment by fstigre** [comment]
One last question, Is the `LinkingObjects` recommended for One to Many relationships?

**Comment by caiyue1993** [comment]
Yes, it's recommended as said in the `README` file:
> Thanks to the CKReference in the CloudKit, IceCream has supported many-to-one relationship nicely. As the Dog example shows, a dog may have an owner. And we'll wrap the owner up as CKReference and push them to the CloudKit.
Inversely, the Person object has a dogs property which is the type of LinkingObjects. So we've successfully supported to-many relationship with a nice workaround. All make sense.

**Comment by fstigre** [comment]
The README file only mentions the `Many-to-One` relationship but nothing about One-to-Many.

**Comment by caiyue1993** [comment]
Let me clarify this. The `List` structure is still not supported in IceCream and you can only use type `LinkingObjects` to implement `to-many` relationship as a workaround. If you are only using `many-to-one`(for example, `Dog` has an owner property which is `Person` type), you don't need to use `LinkingObjects` at all.

**Comment by fstigre** [comment]
Again, I'm using `One-to-Many` NOT `Many-to-One`.  Any idea when `List` will be supported?  Don't get me wrong, the library it's awesome but the `List` is a must for me.  I'm definitely willing to donate to get that feature.

**Comment by caiyue1993** [comment]
I'm currently spending my leisure time working on this feature. It makes sense and you could try looking at the #206 in advance.

**Comment by caiyue1993** [comment]
Hi @fstigre,
I don't know whether you are still sticking around, but I'd like to say that the issue that you described has been fixed in the #206. 

Please refer to the README for the detailed usage. Thank you still.
