### ISSUE TITLE
Crash on mmap

### ISSUE THREAD

**Issue by aehlke** [caiyue1993/IceCream#205]
## Expected behavior
No crash on sync.

## Actual behavior(optional)
Crash on sync.

```
Thread 18: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 28311552 offset: 67108864" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 28311552 offset: 67108864, Error Code=9}
```
![image](https://user-images.githubusercontent.com/71601/86495299-d4933900-bd46-11ea-974b-5f2bae7bb5d2.png)

## Reference links(optional)

Realm recommends using autoreleasepool when using Realm in threads. Should the BackgroundWorker.shared.start inner block be wrapped in an autoreleasepool to possibly resolve this?

**Comment by aehlke** [comment]
I tried adding autopoolrelease and get the same crash, maybe this is not IceCream's fault:

![image](https://user-images.githubusercontent.com/71601/86500543-dddccf80-bd5f-11ea-9611-274b7c67c22a.png)

**Comment by aehlke** [comment]
Looks like this is a Realm issue with many people running into it: https://github.com/realm/realm-cocoa/issues/6572

Regardless, it does seem like this ought to have autoreleasepool per Realm's docs?

**Comment by Fonceur** [comment]
I'm also getting that issue with Realm 5.1.0.

**Comment by caiyue1993** [comment]
It should not be an issue of IceCream. Someone says that downgrading Realm to 4.4.1 helps: https://github.com/realm/realm-cocoa/issues/6572#issuecomment-653699788

**Comment by aehlke** [comment]
Thanks. Does the inclusion of autoreleasepool make sense there regardless?
