### ISSUE TITLE
Two way Sync

### ISSUE THREAD

**Issue by ahamedsaifudeen** [caiyue1993/IceCream#21]
Does this library handle two-way sync? Let's say we have one record per day (tracking user steps taken every day), user's data is synced for 10 days, the user deletes the app and installs again, the previous 10 days data will be available locally after the sync?

**Comment by caiyue1993** [comment]
Yes. That's exactly what IceCream does for you.

**Comment by ahamedsaifudeen** [comment]
Awesome. 

A couple of questions:

1. Does the library create the RecordType in CloudKit by itself?
2. Does the data get into user's private db?

**Comment by caiyue1993** [comment]
1. Yes. The default RecordType is the name of your Object class, btw.
2. Yes.

**Comment by ahamedsaifudeen** [comment]
Great. Thanks again.
