### ISSUE TITLE
Swift package target 'Realm' is linked as a static library by 'IceCream' and 'RealmSwift'. This will result in duplication of library code.

### ISSUE THREAD

**Issue by ts95** [caiyue1993/IceCream#213]
I'm getting the following error with the preview canvas in my SwiftUI project with Xcode 12 beta 3:

 ```
Swift package target 'Realm' is linked as a static library by 'IceCream' and 'RealmSwift'. This will result in duplication of library code.

----------------------------------------

SchemeBuildError: Failed to build the scheme "MyApp"

Swift package target 'Realm' is linked as a static library by 'IceCream' and 'RealmSwift'. This will result in duplication of library code.

Build system information:
error: Swift package target 'Realm' is linked as a static library by 'IceCream' and 'RealmSwift'. This will result in duplication of library code.
```

I'm using SPM to depend on IceCream v1.13.1:
![image](https://user-images.githubusercontent.com/1880556/88861554-7b5fdd80-d1fe-11ea-93bc-c03a486e4ede.png)

The project still builds and I can run the app in the simulator, but the canvas feature doesn't work at all.

**Comment by ts95** [comment]
It appears that the issue is related to this: https://github.com/realm/realm-cocoa/issues/6625

**Comment by TizianoCoroneo** [comment]
Remove `Realm` from here in you Package.swift: 
`dependencies: ["RealmSwift", "Realm"],`

The Realm module is already linked by RealmSwift.

**Comment by ts95** [comment]
As of Xcode 12 beta 5 this is no longer a problem 👍
