### ISSUE TITLE
BackgroundWorker may not  be thread safe

### ISSUE THREAD

**Issue by jeffssss** [caiyue1993/IceCream#216]
I read both `BackgroundWorker` and `https://academy.realm.io/posts/realm-notifications-on-background-threads-with-swift/` and I found that maybe `BackgroundWorker` is not thread safe.

when I call `BackgroundWorker.shared.start(_)` simultaneously in other threadA and B (A and B save difference data), There is a certain probability that BackgroundWorker execute A or B twice.

I wonder if it's really a problem? or if it is conformance to expectation。

**Comment by Cliff-F** [comment]
This certainly happens. It is not thread safe.

**Comment by Cliff-F** [comment]
I added synchronized blocks when accessing block: (() -> Void)
```
      objc_sync_enter(self)
      self.block = block
      objc_sync_exit(self)  
```
```
    objc_sync_enter(self)
    block?()
    objc_sync_exit(self)
```
Here's the crash log from Crashlytics.
![screenshot](https://user-images.githubusercontent.com/1606507/117605456-d9691a80-b1ab-11eb-872a-764caf78af5d.png)
