### ISSUE TITLE
CKAsset support

### ISSUE THREAD

**Issue by MrFuFuFu** [caiyue1993/IceCream#22]
Does IceCream support CKAsset. I'm using CloudKit, and there are some images needs to save in iCloud. I didn't find some code about CKAsset. 

Will you support it in the future if you haven't support it yet?

**Comment by MrFuFuFu** [comment]
Oh. It support `Data` type. I think we can use `Data` instead.

**Comment by insidegui** [comment]
Maybe IceCream could detect if the data is too large for a simple `Data` field and automatically switch to `CKAsset`. Apple recommends that anything more than a few kilobytes in size be stored as a `CKAsset` instead of `Data`.

**Comment by MrFuFuFu** [comment]
@insidegui  Yeah. That's why I ask this question. And there is another problem need to consider. 

If there are many images or files I need to save in Realm. It's not a good idea for saving these data into Realm's `Data` type. Instead, they should be saved as file paths.

So, is there any plan for saving and syncing these big data in IceCream?

**Comment by caiyue1993** [comment]
Hi @MrFuFuFu, you've raised a good issue. IceCream hasn't implemented a appropriate way to handle assets storage for the time being. 

However just like @insidegui said, large data should be stored as `CKAsset`. We think IceCream should take care of it in the near future. 

As for the another problem that you mentioned, we need to dig further. We'll let you know if have results. 

Thank you again and we're glad that you can join us!

**Comment by MrFuFuFu** [comment]
@caiyue1993  Cool, I'm waiting for that. I hope it will come very soon. As it's quite urgent for my current situation. 

I will also try to work on that. ^ ^

**Comment by caiyue1993** [comment]
Feel free to checkout a new branch and make your contributions! 😃

**Comment by caiyue1993** [comment]
#24 was merged successfully and hooray! 🎉   

Readme is also gonna be updated soon.

**Comment by MrFuFuFu** [comment]
Awesome! Thank you so much.
