### ISSUE TITLE
Less verbose logging/printing in console

### ISSUE THREAD

**Issue by NerdyTherapist** [caiyue1993/IceCream#23]
Currently, IceCream is `print`ing a lot of information to the console. Most of the time, I don't need as much information (like every database item). The many logs sometimes even get in the way of development, as I have trouble finding my own debug log outputs.

I would love it if logging could be optional. This could be achieved either through delegation, where the delegate functions receives information about the sync status or errors, which I can then print if I want to. The other way (I think) would be through completion handlers / closure blocks that provide information, that I can also decide on whether to print or not. 

Is this something useful or needed, or is there some other way to turn off logs from a framework?

**Comment by caiyue1993** [comment]
Hi @NerdyTherapist , thanks for issuing this concern. This issue certainly has bothered you guys a lot.
And my thoughts is, we don't need to add a delegation or something else to solve this. That's too redundant. We may just need to add a compiler flag and let you to choose whether to show the log. I'll dig into this.

Or I could just remove this database item log. It's not necessary. 

I'll let you know if I have my decision.

**Comment by insidegui** [comment]
I suggest using the new [os_log system](https://developer.apple.com/library/content/samplecode/Logging/Introduction/Intro.html). I've been using that on my work and it really helps.

**Comment by caiyue1993** [comment]
@insidegui Thanks man! I'll try it 😉

**Comment by NerdyTherapist** [comment]
Well, I wouldn't want to remove the logging entirely. In fact, I think it's really helpful setting up the framework and debugging an error to see what's going on inside; I definitely needed it in the beginning. That's why I would still somehow return the information but leave it up to the individual developer to show or hide it. 

@insidegui I'm not too familiar with os_log, but is it possible to filter out some of these logs in the Xcode console? If yes, that sounds like a good solution.

**Comment by insidegui** [comment]
> I'm not too familiar with os_log, but is it possible to filter out some of these logs in the Xcode console? If yes, that sounds like a good solution.

I believe it is, but I've been using the Console app to look at logs lately, since there you can filter the logs with various criteria and it shows colored dots for errors which makes them stand out.

**Comment by caiyue1993** [comment]
Hi @NerdyTherapist , I hope you are still stick around. 
After some researches, for the time being I've found that the easiest implementation is add a global property. So, if want to turn off the log info which comes from IceCream, you just need to set 

`IceCream.shared.enableLogging = false` .

The default value is true. Check things out at #28 .

The implementation of compiler flags also works, but it takes more effort for developers in integrate. So for now I just don't think about it.
