### ISSUE TITLE
Primary key Support ObjectId ( Realm - ObjectId.generate())

### ISSUE THREAD

**Issue by WelkinDev** [caiyue1993/IceCream#239]
Behavior:
As I use ObjectId as primary key, app will crash when set CreamAsset property

Suggestion:
Try to pass ObjectId as String or Int when use ObjectId as primary key, and exchange to ObjectId after sync complete

**Comment by WelkinDev** [comment]
Or use ObjectId.generate().stringValue, will it cause other problem?

**Comment by mohitnandwani** [comment]
You can use` UUID().uuidString` instead for generating random ids if ObjectID.generate is causing any issues. Other than that, how are you setting the primary key? AFAIK only int and string primary values are currently supported.

**Comment by WelkinDev** [comment]
`UUID().uuidString` method I used before, but some strange problems can occur on MacOS. `ObjectId.generate()` is fine. 
Now the code looks like this, Everything seems normal now.

`@objc dynamic var identifier = ObjectId.generate().stringValue
override class func primaryKey() -> String? { return "identifier" }
`
