### ISSUE TITLE
Cannot build Project because "ListBase" does not exist

### ISSUE THREAD

**Issue by elliotcz97** [caiyue1993/IceCream#241]
When i want to build my project i get the error `Cannot find type 'ListBase' in scope`

I'am using the newest version of every pod!

RealmSwift (10.8.1),
RxSwift (6.2.0),
IceCream (2.0.2)

Is this a bug on my side, or is it a change within Realm?

Looking forward to help from you guys!

**Comment by elliotcz97** [comment]
I have found an issue on the realm-cocoa github, hope it might help:

https://github.com/realm/realm-cocoa/issues/7288

**Comment by faizy-ahmed** [comment]
This resolved my issue.
Use `RLMSwiftCollectionBase` instead of `ListBase` in new version.
Original Source: https://github.com/caiyue1993/IceCream/pull/256#issuecomment-1034336992
