### ISSUE TITLE
How to create only one zone?

### ISSUE THREAD

**Issue by Mr-ZNN** [caiyue1993/IceCream#245]
> Below is the issue template. You can fill each part then submit your issue. 
> Or you can just delete all of these and describe your questions in you-like style. 
> But please remember: the more detailed info you offered, the greater possibility your problem will be solved. 😜

## Expected behavior
By default, a zone will be created for each record, How to create only one zone for all records?

// Please replace this line with your expected behavior.

## Actual behavior(optional)

// Please replace this line with the actual behavior.

## Steps to reproduce the problem(optional)

// Please provided to steps to reproduce the problem

## Reference links(optional)

// Please offer the reference links to us. We appreciate it.

**Comment by caiyue1993** [comment]
No, this is not supported in IceCream. However, you could customize your own engine code to suit your needs.
