### ISSUE TITLE
请教一下，当我同时需要同步私有库和公共库的时候，应该用哪种写法呢？

### ISSUE THREAD

**Issue by DLsunset** [caiyue1993/IceCream#255]
![1642038285529](https://user-images.githubusercontent.com/24959524/149251148-de67b5bb-186e-4068-bf84-7cee6870c85a.jpg)
![1642038319624](https://user-images.githubusercontent.com/24959524/149251162-5ae0f571-add0-4a87-a35d-4e812515d35d.jpg)
这两种哪个是正确的呢？还是都不正确？

**Comment by caiyue1993** [comment]
Hi @DLsunset, the second one is the preferred way and the first one won't work as you expected.
However, I suggest you put private/public model into different Realms and pass Realm configurations into the `SyncObject` initializer.
I'll produce a detailed usage in the README later. Thank you!

**Comment by dong706** [comment]
but I'm unable to get the code to work correctly. Specifically, I'm able to synchronize the private database but not the public one. Could you assist me in resolving this?

**Comment by dong706** [comment]
I need to synchronize both private and public database simultaneously, which approach should I take?
