### ISSUE TITLE
Workaround for using references?

### ISSUE THREAD

**Issue by StefanDesu** [caiyue1993/IceCream#27]
Hi,

I was looking for a way to sync my Realm database with CloudKit, and IceCream seems to be the best solution for it. However, I'm using references in my Realm database and IceCream doesn't seem to support those yet. Would it be a viable workaround to save the ID of an object instead of the object reference?

Thank you,
Stefan

**Comment by caiyue1993** [comment]
Hi @StefanDesu , thank you for the recognition. And the references that you said have not been supported yet, related issue was #5. 
But this feature is on the to-do list, it gonna be supported in the future. (If you are in a big burry, you could fork this project directly to do your changes 😉
