### ISSUE TITLE
CreamAsset uniqueFileName

### ISSUE THREAD

**Issue by aplusm** [caiyue1993/IceCream#29]
Hi,

What's the purpose of appending an UUID to the uniqueFileName property ?

`self.uniqueFileName = "\(uniqueKey)_\(UUID().uuidString)"`

The use-case i'm facing is the update of an image asset for the same object (i.e same unique key).

From the API, i suppose the proper way of updating an asset is by recreating a CreamAsset object. In this case, the uniqueFileName property will be a new unique one, and the 2 images will be stored on the userDevice.

Am i missing something ?

**Comment by caiyue1993** [comment]
Hi @aplusm , you've raised a great issue.
> What's the purpose of appending an UUID to the uniqueFileName property ?

Considering this situation, a Dog object may contain one more CreamAsset. We need to add an UUID to differentiate these asset. @MrFuFuFu Am I right?

It's true that we may have redundant files. And we will optimize its logic in the future release. We've discussed this issue in the #24 and you could check it.

Your proposal adding a `prop` is a good alternative but a new magic string was involved. So this is also a problem.

**Comment by MrFuFuFu** [comment]
Hi @aplusm , @caiyue1993  Yeah.  it's right.

A Dog object may contain more than one `CreamAsset`. Using Dog's id and asset's id to unique a file. Once one of CreamAsset set as `nil` in a Dog object, we can using this `uniqueFileName` to filter redundant files. As @caiyue1993  said. For now it still may have redundant cache files. That's the problem need to be solved in the future.

**Comment by aplusm** [comment]
Hi @caiyue1993 , @MrFuFuFu 

I see 2 major flaws in this design :

- **Redundant files:** For medium/large asset, this is really problematic as we can rapidly use a massive amount of user device storage.
_Use-Case_: In a drawing app, user is drawing and a snapshot of its progression is saved every x seconds.

- **Deletion of CreamAssets:** Right now, deletion of assets is based on object’s recordID. This works in the example as dog.id is used as the uniqueKey but if i use any other string as a key (e.g: any UUID), the file will never be deleted. 
Ex: 
`dog.avatar = CreamAsset(uniqueKey: "DOG_\(UUID().uuidString), data: imageData)`
This CreamAsset will never be deleted by `CreamAsset.deleteCreamAssetFile(with id:)`

To prevent this bug, the presence of the primary key must be enforced in the asset filename (cf my proposal of the object parameter in `CreamAsset.init`)

Regarding the new `prop` parameter to the init of CreamAsset, it is a mere replacement of the `uniqueKey` parameter, not a new one.

**Comment by caiyue1993** [comment]
@aplusm You've really got the point. It's truly 2 major flaws and needs to be reconsidered. 
You could contribute to this by pulling a request directly, that would be very nice :)

**Comment by aplusm** [comment]
Hi guys,

Following our conversation,  i started some coding regarding CreamAsset.

No PullRequest yet, but if you want to take a look:
https://github.com/caiyue1993/IceCream/compare/master...aplusm:ckasset

**Comment by aplusm** [comment]
Opened PR #32
