### ISSUE TITLE
README.md : Add Entry for remote notifications setup

### ISSUE THREAD

**Issue by aplusm** [caiyue1993/IceCream#30]
In the Usage part of the README.md, a section should be added regarding remote notifications.

Otherwise, by default, no remote notifications will be synchronised by the SyncEngine.

The code presents in the _Example_ could be a good start : 

 ```
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        let dict = userInfo as! [String: NSObject]
        let notification = CKNotification(fromRemoteNotificationDictionary: dict)
        
        if (notification.subscriptionID == IceCreamConstant.cloudKitSubscriptionID) {
             NotificationCenter.default.post(name: Notifications.cloudKitDataDidChangeRemotely.name, object: nil, userInfo: userInfo)
        }
        completionHandler(.newData)
        
    }
```

**Comment by caiyue1993** [comment]
Thanks. I've appended this as the Step 4 in the [Usage](https://github.com/caiyue1993/IceCream#usage) section. You could check it out. (Since I don't want to add too much info on the main page, so I keep it as cleaner as possible)
