### ISSUE TITLE
404 on contribution link

### ISSUE THREAD

**Issue by matadan** [caiyue1993/IceCream#38]
> Below is the issue template. You can fill each part then submit your issue. 
> Or you can just delete all of these and describe your questions in you-like style. 
> But please remember: the more detailed info you offered, the greater possibility your problem will be solved. 😜

## Expected behavior

// Please replace this line with your expected behavior.

## Actual behavior(optional)

// Please replace this line with the actual behavior.

## Steps to reproduce the problem(optional)

// Please provided to steps to reproduce the problem

## Reference links(optional)

// Please offer the reference links to us. We appreciate it.

**Comment by caiyue1993** [comment]
Thank you. I've already fixed it :)
