### ISSUE TITLE
Support iOS 10.0

### ISSUE THREAD

**Issue by jianilii** [caiyue1993/IceCream#48]
## Expected behavior

Support minimum deployment target iOS 10.0

## Actual behavior(optional)

The minimum deployment target is iOS 11.2 right now

**Comment by dev-tsc** [comment]
Hi, I have the same issue with the deployment target. The value seems to be set to [11.2](https://github.com/caiyue1993/IceCream/blob/33da28d7dda6a3daefc97f9c2b35ade5285f0426/IceCream.xcodeproj/project.pbxproj#L264), not only for the example project.

**Comment by caiyue1993** [comment]
@dev-tsc So were you using Carthage?

**Comment by dev-tsc** [comment]
Yes, I was using Carthage @caiyue1993 since Cocoapods is not an option right now.

**Comment by caiyue1993** [comment]
Hi guys. It was my mistake for not correctly setting IceCream project deployment target. And this issue was fixed in #50 and was merged into master. So now, you could use IceCream via Carthage on 10.0 deployment target.
