### ISSUE TITLE
Does IceCream support CKReference & Realm's LinkingObjects?

### ISSUE THREAD

**Issue by RocZhang9673** [caiyue1993/IceCream#5]
Thank you for your great work!

I'm try to extension my already exists realm object with IceCream's CKRecordConvertible & CKRecordRecoverable, And may I wonder does IceCream support CKReference & Realm's LinkingObjects? 

For example:

I have a realm object like this:

class HistoryRecord: Object {
  @objc dynamic var ckRecordID = NSUUID().uuidString
  @objc dynamic var isDeleted = false
  @objc dynamic var updateTime: TimeInterval = Date().timeIntervalSince1970
  @objc dynamic var linkedDigest: LocalDigest?
}

I used to save the "LinkedDigest" as a CKReference in CloudKit.
And how about the Realm's LinkingObjects?

**Comment by caiyue1993** [comment]
Happy to receive your reply!

Now as a early version, IceCream only support single Object model. But supporting CKReference & Realm's LinkingObjects is already on the [to-do list](https://github.com/caiyue1993/IceCream#to-do-list) which means we will support it in the later commits.

Or you can change code directly and raise a PR to us!

**Comment by liakhandrii** [comment]
Hi! I'd love to use this lib in my app, but it's useless without the relations for me. 
I'd like to help you implement this functionality, but I need some clues on where to start from.

**Comment by caiyue1993** [comment]
Hi @liakhandrii , thanks for your trust of IceCream. You could simply start by forking this project and prepare your commits. My suggestion is to read the source code of IceCream(it's simple!), and do your research of CKReference & Realm's LinkingObjects. Then you might get some idea. 
Just ask me if you need any help and we're looking forward to your contribution. :)

**Comment by RockerHX** [comment]
You might also use record IDs is when you cannot use a CKReference object to refer to a record. References are only valid within a single zone of a database. To refer to objects outside of the current zone or database, save the strings in the record’s CKRecordID and CKRecordZoneID objects. When you want to retrieve the record later, use those strings to recreate the record and zone ID objects so that you can fetch the record.

**Comment by dbmrq** [comment]
I've opened a bounty for this on Bountysource: https://www.bountysource.com/issues/52087619-does-icecream-support-ckreference-realm-s-linkingobjects

**Comment by remaerd** [comment]
I wished someone who can finish this for me. But I have a tight schedule and I can't wait. So this is me trying to implement this feature.

#67 

It currently supporting one-to-many relationship only. I'm not familiar with the architecture of List<Object>. So it may take time to implement this feature.

Cheers.

**Comment by caiyue1993** [comment]
Hi guys,

I've implemented the [to-one relationships](https://realm.io/docs/swift/latest/#many-to-one) of Realm in #74 using the CKReference. You can take a look on that.
And @remaerd has offered his way of implementing [to-many relationships](https://realm.io/docs/swift/latest/#many-to-many) which is still worth discussing. So it still needs time to find a better way. 
As for [LinkingObjects](https://realm.io/docs/swift/latest/#inverse-relationships), it has the dependency on the to-many relationships so it hasn't been supported yet. 
So this pr is gonna be closed for now. And check #75 for later update.
