### ISSUE TITLE
Error with multiple objects

### ISSUE THREAD

**Issue by bitomule** [caiyue1993/IceCream#51]
## Expected behavior

I´ve multiple Realm objects and I expected them all to sync with Cloudkit but only some do. I just call and store reference of multiple SyncEngine<MyObject> references. Is that supported?

## Actual behavior(optional)

Only some syncEngines seem to work.

**Comment by caiyue1993** [comment]
Duplicated issue is #5. You may help us to contribute to this project.

**Comment by bitomule** [comment]
But I'm not talking about objects with references. I mean I've different objects types I want to sync like: Trip, Transport... 

I'm trying to find why it fails and now I've found that CloudKit does not support keys that start with underscore, I´ll try to create a PR adding this to the readme so other users understand faster why it fails.
