### ISSUE TITLE
Nested frameworks and submission failure 

### ISSUE THREAD

**Issue by dev-tsc** [caiyue1993/IceCream#56]
When preparing an app that depends on IceCream (via Carthage) for the Store/Testflight the following errors are given: `...contains disallowed nested bundles` and `...contains disallowed file 'Frameworks'`. 

The project itself depends on `realm-cocoa` as well, so in addition, I get `CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value…` for `Realm` and `RealmSwift`.

It is my understanding this is due to the [copy framework script](https://github.com/caiyue1993/IceCream/blob/5bcd0c035cfcd0965067d14b36a08aed93f445ac/IceCream.xcodeproj/project.pbxproj#L180). While this seems to work during runtime (and on my device), it causes submission problems. So the copy framework phase should probably be removed and only happen at the app level.

Similar discussions I found regarding this issue:
- https://github.com/Carthage/Carthage/issues/416
- https://github.com/Carthage/Carthage/issues/844#issuecomment-147783855
- https://github.com/tristanhimmelman/AlamofireObjectMapper/pull/8

**Comment by fouquet** [comment]
I had the same issue. My solution was to fork the project, remove the copy step from the build phases and point Carthage to my repository. Works fine.

I suppose there are good reasons why there is this step (local development comes to mind), so I'm hesitant to just create a pull request for my changes, though.

If anyone wants a quick solution for this problem, change your Cartfile entry to `github "fouquet/IceCream"`

**Comment by caiyue1993** [comment]
Hi @dev-tsc @fouquet , many thanks for your feedback. I'm currently looking into and doing some research over this issue.

**Comment by caiyue1993** [comment]
@dev-tsc @fouquet Thanks for your detailed information and I've found out that the reason for this is due to the collision of `Realm` and `RealmSwift` in the app bundle. As the pic showed following: 

![issue](https://user-images.githubusercontent.com/6007760/40662764-dc1dd6ee-6389-11e8-9326-8412f24f2c5d.png)

The appropriate solution to this is to remove `$(SRCROOT)/Carthage/Build/iOS/Realm.framework` and `$(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework` in `Input Files`. So `Realm` and `RealmSwift` will not be copied to the folder of Framework one more time.

**Comment by rodericj** [comment]
@fouquet we've pulled your commit into https://github.com/thumbworks/IceCream/tree/remove-carthage-copy-script and at first glance it seems to fix our archive builds but our development builds are all complaining at run time 
```
dyld: Library not loaded: @rpath/Realm.framework/Realm
...
Reason: image not found
```

**Comment by sprynmr** [comment]
The solution here was not correct. The build script needs to be removed entirely from the framework per https://github.com/Carthage/Carthage/issues/844#issuecomment-147783855. The dependencies (Realm) can be listed in the Cartfile of the framework with the appropriate version number. This will let Carthage do dependency management should the consumer's app require the same framework. They will still have to include that framework manually, similar to how they include IceCream, but that makes sense.

**Comment by fouquet** [comment]
@rodericj This is odd, it's working fine for me 🤔

**Comment by caiyue1993** [comment]
@sprynmr Thanks bro. You're right as "The dependencies should all linked and copied at the app-level". Close this issue and check #71.
