### ISSUE TITLE
Sync Public iCloud databases

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [caiyue1993/IceCream#58]
Please can a switch be implemented so that we can choose to synchronise private or public iClod databases?

**Comment by caiyue1993** [comment]
Hi @ianbradbury-bizzibody , I've already known your requirements. And this could be the next feature that IceCream will support.

**Comment by ianbradbury-bizzibody** [comment]
Thank you,

**Comment by real1900** [comment]
I am also looking forward to support for public database :)

**Comment by ianbradbury-bizzibody** [comment]
Any news?  Wha you have achieved so far is amazing - please this one next feature?

**Comment by caiyue1993** [comment]
@ianbradbury-bizzibody It would be, ib 😊

**Comment by caiyue1993** [comment]
Hi all(especially @ianbradbury-bizzibody ),

Finally, IceCream has supported public database. See #24 for more info.

**Comment by ianbradbury-bizzibody** [comment]
:)

I will be all over this later today/tomorrow!  :)
