### ISSUE TITLE
Many-to-many relationship support

### ISSUE THREAD

**Issue by caiyue1993** [caiyue1993/IceCream#75]
Related link: [Many-to-many relationship in Realm](https://realm.io/docs/swift/latest/#many-to-many)

#68 provided a way of implementing this feature but it's not that neat. It has used a internal class(`ListBase`) of Realm which is not recommended. So this issue is trying to collect a better way of implementing this feature.

**Comment by ewerx** [comment]
Does IceCream support Realm's `List` now? For example can you do this?
```swift
class Person: Object {
   //...
   var dogs = List<Dog>()
   //...
}

class Dog: Object {
  // ...
   let owners = LinkingObjects(fromType: Person.self, property: "dogs")
  // ...
}
```

**Comment by caiyue1993** [comment]
Sorry. The answer is no right now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by geniuscd** [comment]
:/ any news on this feature? I know that there is many-to-one, but in some apps the following code architecture is not recommended.
