### ISSUE TITLE
Optimize the perform order of methods in SyncEngine

### ISSUE THREAD

**Issue by caiyue1993** [caiyue1993/IceCream#77]

**Comment by bitomule** [comment]
I think that we need tests before we move forward. What do you think? If we add tests, should we add them using a demo project or just create a Tests project and maybe in the future we add a Demo project too.

Once we have a tests project I can create a RemoteDataSource that can be mocked so we can easily test without requiring real CloudKit.

**Comment by caiyue1993** [comment]
Yes @bitomule , actually adding test functionality is already in my plan. And I'll do my research and find the best test way of IceCream. However, you could have a try yourself first. Feel free to do that.

**Comment by bitomule** [comment]
Ok @caiyue1993, I´ll try to create a PR with:

- Tests proyects
- CloudKitDataSource (remove CloudKit calls from the SyncEngine so they can be mocked)
- Tests

**Comment by caiyue1993** [comment]
We've created #94 regarding this issue. Now the `registerLocalDatabase` method is called when `createCustomZones` completes successfully. It's much more reasonable. 

Check that out. Thanks.
