### ISSUE TITLE
Use one SyncEngine for multiple Objects

### ISSUE THREAD

**Issue by harryworld** [caiyue1993/IceCream#8]
Reference to Realm Object Server, it registers the types to be synced to server once at launch.

**Comment by caiyue1993** [comment]
I have already known your requirements from the title. It has been added on the to-do list. Thank you.

**Comment by IngmarStein** [comment]
Hey @janandre, would you mind creating a PR with your changes if you want them merged?

**Comment by caiyue1993** [comment]
Hi @janandre , glad to hear that you will use IceCream in your app and your commits look great! 

So as @IngmarStein said, would you mind creating a PR first so that we could review your job more clearly?

**Comment by janandre** [comment]
@IngmarStein @caiyue1993 do you want to create a feature branch before, or should i just make a PR to master?

**Comment by caiyue1993** [comment]
@janandre You could just create a new branch yourself and make a PR to master, yes.

**Comment by ianbradbury-bizzibody** [comment]
Is there any news on this capability being implemented?

**Comment by caiyue1993** [comment]
@ianbradbury-bizzibody Check #40 for the newest discussion. Just be patient.

**Comment by ianbradbury-bizzibody** [comment]
Hey.  Sorry - I did not see that conversation.  This is really good news - good steps in the right direction.

**Comment by matadan** [comment]
@ianbradbury-bizzibody This is now PR #42. I just got it working with both private and public objects. But I ended up changing a lot of files so it needs a lot of checking and testing to see if it can be accepted.

**Comment by ianbradbury-bizzibody** [comment]
:)

I'll try and find some time tonight to test.   

Exciting!

**Comment by matadan** [comment]
Use IceCreamExample2 on 2 devices to add Cats and Dogs. Or 1 device and the cloudkit dashboard. I'll fix up the example so that the private and public sheets work and incorporate assets as in the original example too.

**Comment by ianbradbury-bizzibody** [comment]
I can't find IceCreamExample2

Can you point me to it?

**Comment by matadan** [comment]
There should be an Examples folder in the per-object-database-selection branch of my fork:

https://github.com/matadan/IceCream.git

**Comment by matadan** [comment]
@ianbradbury-bizzibody I've put this in the master branch of my fork as 1.4.0.

https://github.com/matadan/IceCream.git

**Comment by caiyue1993** [comment]
Hi guys,

The multiple objects syncing ability gonna be supported in the #55. And it's now waiting for the final polishing and tests. I'd appreciate it if you have time to look inside that implementation and give us advices if you have. Or you could help us test the code yourself, that would be grateful.
Thanks.

**Comment by caiyue1993** [comment]
#55 was successfully merged. This issue is gonna be closed, finally. :)
