### ISSUE TITLE
Zone not found, first sync fail

### ISSUE THREAD

**Issue by timefrancesco** [caiyue1993/IceCream#83]
Hey guys, this library is awesome thank you for creating it.  
I've noticed that when launching the SyncEngine the first time it syncs, I get the following errors:  
` "ErrorHandler.Fail: Zone Not Found: the specified record zone does not exist on the server.CKError.Code: 26"`.  

I checked the code and I noticed that in the init, the `createCustomZones` function is called after `syncRecordsToCloudKit`, so I believe this is why I get the errors.  

The flow I use in the app is the following:  
iCloud is disabled by default, the user can add objects to realm and use the app.  
In Settings I've a toggle to turn iCloud on, when that happens the SyncEngine gets initialized.  

At the moment as a workaround I just call  `syncRecordsToCloudKit` after the init and that solves the problem.

Thank you.

**Comment by bitomule** [comment]
I think this is related to https://github.com/caiyue1993/IceCream/issues/77

**Comment by caiyue1993** [comment]
Hi @timefrancesco , thanks for your detailed information and we've noticed this situation. 

The error message you mentioned usually appears the very first time `SyncEngine` gets initialized, which means custom zones are not created when doing some syncing stuffs. To be more specific in IceCream, means either `syncRecordsToCloudKit` or `fetchChangesInDatabase` is called before `createCustomZones` method.

And this situation is not happened always because the CloudKit API is highly asynchronized. We don't know which order the methods were executed on the iCloud. 

So we will make it better and trace this issue in #77. If you have any questions, just leave your comments. Thanks.

**Comment by caiyue1993** [comment]
In addition, IceCream hasn't supported the flow that you use very well. As [this line](https://github.com/caiyue1993/IceCream/blob/7ffbb884ccb5cfb2a3321e837d8c1b23f602db6a/IceCream/Classes/SyncObject.swift#L119) indicates, the `.initial` case is triggered when your user turns iCloud to on. And we did nothing sync stuffs for this.

@bitomule has already opened an issue #84 for this. We'll fix it.

**Comment by timefrancesco** [comment]
@caiyue1993 yep I noticed that so I push my db objects manually with `syncRecordsToCloudKit` after initing the SyncEngine.   
Seems to work well so far, it's already in production in my [Bitfolio app](https://bitfolio.app).  
Keep up the good work :)

**Comment by caiyue1993** [comment]
@timefrancesco , #94 optimizes the order of functions which fixed this issue. And we've provided a `pushAll` method. Check that out🙂

**Comment by timefrancesco** [comment]
Great, I’ll give it a try! Thank you, great work!

**Comment by johnnyperdomo** [comment]
@timefrancesco how did you go about syncing the records to cloudkit? 

This is how i initialized my sync Engine in app delegate. 
```
 syncEngine = SyncEngine(objects: [
            SyncObject<Story>(),
            SyncObject<Thread>(),
            SyncObject<Branch>(),
            SyncObject<Note>()
            ])

        application.registerForRemoteNotifications()
```

It says syncing successful, but no records show for the model objects in cloudkit dashboard. It saved to local realm db. 

Please help, a code snippet would be extremely helpful!!!

**Comment by EricWiener** [comment]
@johnnyperdomo did you get it to work?

**Comment by timefrancesco** [comment]
apologies for the late reply, @johnnyperdomo your code is correct but you need to add a `syncEngine.pushAll()` the first time you turn iCloud on (or the first time the user install the app if it's on by default). 
This will create the zones and everything, need to be called only once.

**Comment by EricWiener** [comment]
@timefrancesco thanks for adding that. Helped me figure it out.
