### ISSUE TITLE
Sync old changes, not only updates

### ISSUE THREAD

**Issue by bitomule** [caiyue1993/IceCream#84]
## Expected behavior

Sync existing realm data to CloudKit.

## Actual behavior(optional)

Objects present in the database before adding Icecream doesn´t sync.

## Steps to reproduce the problem(optional)

Create a realm database without Icecream, add and setup Icrecream to your project. Only updates are pushed to the cloud.

**Comment by dbmrq** [comment]
While this isn't implemented, I think it's useful to mention here that we can use `syncRecordsToCloudKit`, as suggested [here](https://github.com/caiyue1993/IceCream/issues/83#issuecomment-417099480).

In my case, for my `Note` and `Quote` objects, I'm doing this after starting the sync engine:

```swift
let realm = try! Realm()
var recordsToStore: [CKRecord] = []
recordsToStore += realm.objects(Note.self).map { $0.record }
recordsToStore += realm.objects(Quote.self).map { $0.record }
syncEngine?.syncRecordsToCloudKit(recordsToStore: recordsToStore, recordIDsToDelete: [])
```

It seems to be working pretty well.

**Comment by caiyue1993** [comment]
Hi @bitomule @dbmrq ,

I've made a PR #94 regarding this issue. I added a public method named `pushAll` to `SyncEngine`. You may call that method to push all local existing Realm data to CloudKit manually. So you don't have the need the write the code yourself @dbmrq 😊.

However, we should NOT call `pushAll` too frequently only when necessary.

**Comment by dbmrq** [comment]
Awesome, thank you!

One more thing: how about fetching all CloudKit data for the first time? E.g., I have some data from my iPhone and then buy a new iPad and install the app… it needs to get all CloudKit data, not just the changes. Is there something like a `pullAll` method to do that? Or is it already handled automatically?

**Comment by caiyue1993** [comment]
@dbmrq Absolutely, it's already been handled. Actually we've provided a `pull` method, but normally you don't need to call that because it's invoked automatically every time `SyncEngine` gets initialized.

**Comment by dbmrq** [comment]
Fantastic, thanks! 🎉
