### ISSUE TITLE
Custom Local Realm

### ISSUE THREAD

**Issue by annanna** [caiyue1993/IceCream#86]
## Expected behavior

I can define which realm should be synced.

## Actual behavior(optional)

Right now, the default realm is used, sometimes with Cream, sometimes not. (as far as I saw)

## Steps to reproduce the problem(optional)

I noted it because of migration issues. So as described in [Realm Documentation](https://realm.io/docs/swift/latest/#migrations) you can change the Realm-config for local migrations. 

I would love to give the realm I set up as a parameter to the SyncEngine. 
I can provide a small fix if you want.

**Comment by caiyue1993** [comment]
Hi @annanna ,

Feel free to do that. You could add a default value for the parameter you wanna set up so the existing code will not be aware of this modification. And you should tell us how to test your changes.

As for the Cream class, I'll optimize that. 

Thanks.
