### ISSUE TITLE
Hangs when there are too many changes

### ISSUE THREAD

**Issue by dbmrq** [caiyue1993/IceCream#88]
My app gives the user the option to delete all his data and also to restore data from backup files.

When erasing all data, I used `realm.deleteAll()`. Now that I'm using IceCream, I iterate over all my objects and set `isDeleted` to `true`.

Then, when restoring data, I go over a different Realm database and use `realm.create()` to add it to the current Realm.

Now, using IceCream, if I open my app in two devices at the same time, erase all data and then add it back from a backup file, the app will receive the `cloudKitDataDidChangeRemotely` hundreds of times and it'll hang forever, making it unusable and requiring me to force quit.

In these cases I think it would be better to group multiple changes together and sync them on a background thread.

**Comment by dbmrq** [comment]
Now that I've been testing this a little further I think it happens even with smaller changes. When two devices are open at the same time, they keep getting many `cloudKitDataDidChangeRemotely` notifications and end up freezing. As soon as I close the app on one of the devices the other one goes back to working fine. I don't get why this is happening… is it possible I'm running into a sync loop, as described here?

> Something you must be aware of when doing this is sync loops. If a change on Realm causes a change on CloudKit and a change on CloudKit causes a change on Realm, we have an infinite loop. To avoid this problem, the sync engine registers a notification token with Realm so changes made by itself don't trigger an upload to CloudKit. (https://medium.com/@guilhermerambo/synchronizing-data-with-cloudkit-94c6246a3fda)

Does IceCream handle this?

**Comment by caiyue1993** [comment]
Hi @dbmrq , as the following line indicates, we've already handled this situation to avoid the loop.

https://github.com/caiyue1993/IceCream/blob/117126c42c92d55bc0d050edbc082e816d37910c/IceCream/Classes/SyncObject.swift#L84 

Thanks for the feedback. I'll test myself to reproduce this issue and let you know.

**Comment by dbmrq** [comment]
Thank you, I'll try to come up with an example project showing the issue when I have the time.

**Comment by dbmrq** [comment]
Ok, looking further into this I'm thinking that the first problem is real but the last problem is partly my own fault, although I'm not sure how. I have many different objects, and if I leave some of them out of the sync engine everything seems to work fine. So I think I'm doing too many write operations for one of the objects, causing too many notifications and making the app freeze. Still, I think it should never freeze in any case. Even if there are hundreds of notifications in a single second, they should be handled in background when possible and the interface should never be blocked.

**Comment by caiyue1993** [comment]
@dbmrq Yes. The data operations shouldn't be performed on the main thread. However we have to avoid the too frequent write operations. Or we can think of one way to bunch these operations so that the interface will be notified less time.
I'll catch up with this issue at my leisure.

**Comment by caiyue1993** [comment]
And just now I found: 

https://github.com/caiyue1993/IceCream/blob/117126c42c92d55bc0d050edbc082e816d37910c/IceCream/Classes/SyncEngine.swift#L299

However, the `fetchChangesInDatabase()` should not be performed on the main queue. This might be the bad guy.

**Comment by dbmrq** [comment]
I just used the Time Profiler instrument on my app and triggered the problem. Here's the result for the main thread:

<img width="832" alt="captura de tela 2018-10-10 as 23 27 03" src="https://user-images.githubusercontent.com/15813674/46776922-11520d80-cce4-11e8-8ffb-72f1595bfc34.png">

The worst offenders seem to be `SyncObject.add(record:)` and `SyncObject.registerLocalDatabase()`. Then there are all those Realm functions, but most of them are probably triggered by these two, and I think they could be performed in a background thread.

**Comment by dbmrq** [comment]
Aha! I think I got it now. Looking into it a little further I think my problem is related to using multiple objects with one-to-many relationships.

I have `Book` and `ReadingSession` objects. A book can have many reading sessions (linked with Realm's `LinkingObjects`).

If I add just `SyncObject<Book>()` or just `SyncObject<ReadingSession>()` to the `SyncEngine`, everything works fine: I make a change to a `Book`, get a single notification with `zid = BooksZone` and the `Book` is updated on the other device;  I make a change to a `ReadingSession`, get a single notification with `zid = ReadingSessionsZone` and the `ReadingSession` is updated. The problem starts when I add both objects to the `SyncEngine`. Then, if I make a change to a `Book`, I get a notification with `zid = BooksZone` and, besides that, a notification with `zid = ReadingSessionsZone` for every `ReadingSession` that book has. I assume this happens because the `ReadingSession` has a `book` property populated with the `Book` object, and that object was changed, so it's like the `ReadingSession` changed (but it doesn't actually need to be updated, because it still belongs to the same `Book`, it's only the `Book` that changed).

So if I have a `Book` with 100 reading sessions and I change its title, I should get only one notification with `zid = BooksZone`, but instead I get *101* notifications: the correct one and 100 others with `zid = ReadingSessionsZone`, one for each of the `Book`'s reading sessions. And that's just the tip of the iceberg, because my reading sessions can also have notes and quotes and those should be synced too. So changing a book triggers notifications for the book and all it's reading sessions and all the notes and quotes for each one of those reading sessions. This makes the library pretty much unusable with multiple objects. I get hundreds of notifications for every little change and the app freezes in no time.

So there are two different problems here. One is that those changes block the interface, which shouldn't happen. But the second problem is that there shouldn't actually be that many changes. Let me know if you want me to open a different issue for that.

Also I have no idea how to go about this, I still don't completely understand how this library works. But if you don't have the time to fix it I'd appreciate if you could guide me in the right direction so I can try to do it myself.

**Comment by dbmrq** [comment]
I tried just changing all async operations to the background thread, but apparently it's not so simple.

I think we'd need to do something like this: https://academy.realm.io/posts/realm-notifications-on-background-threads-with-swift/

But I couldn't figure out how to apply it to IceCream. :(

**Comment by dbmrq** [comment]
Progress!

Based on [this SO answer](https://stackoverflow.com/a/41841847/3539651), I did this: https://github.com/caiyue1993/IceCream/compare/master...dbmrq:master

And it's working beautifully! Really snappy! There are still lots of unnecessary write operations because of what I said above, but they're imperceptible to the user.

However, I don't actually think my code is very good. I'm not even sure what's going on there, haha.

Here I start a run loop and add the notification from that run loop:

https://github.com/dbmrq/IceCream/blob/32130f8430259ba547e66b623ad23c10b32b5e55/IceCream/Classes/SyncObject.swift#L121-L124

But then here I create a new `Realm` instance and I think I'm not supposed to do that, I should use the same as in the notification:

https://github.com/dbmrq/IceCream/blob/32130f8430259ba547e66b623ad23c10b32b5e55/IceCream/Classes/SyncObject.swift#L80-L82

And to use the same `Realm` I'd have to make sure the notification and the write operation are running in the same thread, but I never do that, I just go with `.background`, which doesn't always pick the same thread.

If I add the notification in the *main* thread and then try to perform the write operation in a *background* thread, I get a crash at `try! realm.commitWrite(withoutNotifying: [token])` saying that you can't skip a notification in a different Realm, the token and the write operation need to be from the same instance. But with the run loop thing above I just ignored that and it seems to be working fine. 🤷🏻‍♂️

So I don't know if this is really the right way to do it (probably not) or if I'm just getting lucky. It would be great if somebody with more experience than me could look into it. It's still a big progress though. I think this is the main issue and adding the notifications and doing the write operations on a background thread fixes it perfectly. I just don't know if I'm doing it the right way.

**Comment by dbmrq** [comment]
Yeah, I spoke too soon. The `CFRunLoopPerformBlock` part isn't working at all, and the notification token is actually not created. It only seemed to work for me because I tried the new version in one device while still using the old version in the other.

So doing the `SyncObject.add(record:)` part in a background thread fixes the issue, but the notification token has to be on the same realm instance, so this has to run on the same thread as the notification, and I don't know how to do that. :(

**Comment by dbmrq** [comment]
Ok, I think I got it! :tada:

I followed the instructions in the link above and got it working pretty well: https://github.com/caiyue1993/IceCream/compare/master...dbmrq:master

This fixes the problem with the notifications blocking the interface. I can make a PR if you want, but I kind of just winged it based on the link, so my code can probably be improved. It seems to be working pretty well, though, and I just did what it says there, so I think it's fine.

---

Now there's still the second problem: lots of unnecessary changes resulting from the relationships between objects.

[Realm's documentation](https://realm.io/docs/swift/latest/#collection-notifications) does state that notifications include changes in related objects:

> You’re notified about modifications whenever a property of an object in the collection has changed. This also happens for changes on to-one and to-many relationships, although notifications won’t take inverse relationships into account.

So if we're dealing with dogs and owners, for instance, a change to the owner will trigger a notification for changes to the owner and also for changes to all the dogs (because their owner was modified).

It would be great if we could ignore notifications for certain properties, but unfortunately it's not possible yet: https://github.com/realm/realm-cocoa/issues/3704

The way it works now is really inefficient though. We get hundreds of changes and perform hundreds of write operations even when only one of them is necessary. This also causes the relevant change to take a lot longer than necessary to show up in other devices. I make a change in one device and it only appears in the other about 5-20 seconds later… because IceCream is writing many irrelevant changes before it finally gets to the important one.

I don't know what we could do about this though. It looks like for now we're stuck with getting all those Realm notifications, so I guess the only way to improve this is to get the notifications and then decide which changes must be implemented or not. For instance, if there's a change in an owner we'll get notifications for changes in the owner and all his dogs, but we'd have to figure out that just the owner needs to be changed in CloudKit and do just that. I don't know if there's a better way to go about it.

(I deleted some previous comments because they became irrelevant.)

**Comment by ewerx** [comment]
I am running into the same issue with the one-to-many relationships triggering a cascade of updates for child objects when the parent object changes. 

The only solution I have come up with so far is to use foreign key association of parent/child objects. So instead of Dog having an Owner as a stored property it just stores the primary key of an owner and has a convenience property to lookup the Owner by key in the Realm and return it.

**Comment by dbmrq** [comment]
@ewerx That's what I'm doing for now, but queries are significantly slower and you can't deal with sub-properties, like `Results<Dog>.filter("owner.name == %@", "Daniel")`.

It would be great to be able to use real relationships, but for now I don't see how it would be possible. :(

**Comment by dbmrq** [comment]
Just an update: my code mentioned above (https://github.com/caiyue1993/IceCream/compare/master...dbmrq:master) is actually using a lot more CPU than it should, I'm not sure why. It's successfully running the operations in background and they're not blocking the interface anymore, but those background threads keep using 100% CPU each even after the operations are completed.

**Comment by kitlangton** [comment]
@dbmrq I think I've gotten something to work (heavily inspired by your branch). I modified the BackgroundWorker to behave slightly differently, so it behaves sort of like a Realm-enabled background dispatch queue. I've also changed the SyncEngine such that fetching database changes occurs serially (which could be a problem now that we're using a background process).

You may want to try this: https://github.com/kitlangton/IceCream/tree/background-sync

I'm going to clean it up a little bit and submit a PR soon.

**Comment by dbmrq** [comment]
@kitlangton Fantastic, thank you! I’m on a trip right now, so I won’t be able to try this until after the holidays, but it’s looking great! 🍻

**Comment by dbmrq** [comment]
Hello, lovely people! I'm sorry it took me forever, but I was finally able to take a look at @kitlangton's fork and so far it's been working really well! What's missing for a PR? Maybe I can help. :)

**Comment by drmarkpowell** [comment]
+1 to this work, it seems to be working really well and has stopped my app from freezing the UI, which was happening a lot. Also I'm happy to pitch in time if that would help the PR process.

**Comment by caiyue1993** [comment]
Hi guys, thanks for your patience. This issue is about to resolve. 

Please turn to #155 for the latest updates.
