### ISSUE TITLE
Option for syncing

### ISSUE THREAD

**Issue by frasza** [caiyue1993/IceCream#90]
Hey!

First of all, thank you for such a great option to have! Yesterday I was playing with Realm + Realm Platform but then I found out about IceCream and it works like charm.

My question is, could it be possible for user to select either he wants to sync to iCloud or just store locally?
My app is storing record data and I am not sure how Apple is with the way that IceCream automatically syncs to signed Apple account? I would love to have an option i.e. on onboarding part for user to select if he wants to enable sync or not. Is that possible? How are you dealing with this?

Edit: Additional question. If I install app on my device, it works like charm. If I put it on Testflight, friend doesn't get data synced back after reinstall. Is it because I am using Development container and I should deploy to Production?

Thanks,
Zan

**Comment by johnnyperdomo** [comment]
Did you find out how to do this?
