### ISSUE TITLE
Support Realm's Link format

### ISSUE THREAD

**Issue by justJS** [caiyue1993/IceCream#97]
## Expected behavior

IceCream should sync Realm's Link<StandardTypes> format to CloudKit's Arrays.

## Actual behavior(optional)

IceCream completely ignores Realm's Links.

Could IceCream be updated to support Links? (only with the types of Arrays CloudKit supports are needed).

**Comment by caiyue1993** [comment]
Related PR #98

**Comment by caiyue1993** [comment]
#98 has been merged. Now Realm List of **natural types** have been supported.
